{% set name = "jsonnet" %}
{% set version = "0.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 23ffcd4d03a10af7b20b53feee16627debe28345a4d7d5ed07881b7444553bfb

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - _jsonnet

about:
  home: http://github.com/google/jsonnet
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python bindings for Jsonnet - The data templating language

extra:
  recipe-maintainers:
    - nelson-liu
    - michamucha
    - synapticarbors
